import pyNebula as neckPy

print("We are live with pyNebula!\n")

neckPy.addEnt("P1", 0)
neckPy.findEnt("P1")
neckPy.addComp("TransformComp")
neckPy.addComp("GraphicalComp")
neckPy.addCompVar("transform", "matrix")
neckPy.addCompVar("nickname", "PythonGuy")
neckPy.addEnt("P2", 1)
neckPy.findEnt("P2")
neckPy.addComp("TransformComp")
neckPy.addComp("GraphicalComp")
neckPy.addCompVarFloat("xVal", -5.0)
neckPy.addCompVarFloat("yVal", 0.0)
neckPy.addCompVarFloat("zVal", 3.0)
neckPy.addEnt("P3", 2)
neckPy.findEnt("P3")
neckPy.addComp("TransformComp")
neckPy.addComp("GraphicalComp")
neckPy.addCompVarFloat("xVal", 5.0)
neckPy.addCompVarFloat("yVal", 0.0)
neckPy.addCompVarFloat("zVal", 3.0)
neckPy.managerInit()
neckPy.getCompVar("nickname")
neckPy.getCompVar("xVal")
neckPy.getCompVar("entID")
neckPy.getCompVar("GEID")
neckPy.listOfEnt()
neckPy.delEnt("P2")
print("Entity should have been deleted by now, let's see if the entity count is one lower than before!\n")
neckPy.listOfEnt()

print("pyNebula has reached it's end!\n")